Add examples with an ILU(0) preconditioner
JuliaSmoothOptimizers/Krylov.jl pull request #221
Opened 2020-10-19 19:58 UTC by amontoison

`DIOM` and `DQGMRES` work well with ILU(0) preconditioners.
I opened the pull request https://github.com/mcovalt/ILU0.jl/pull/3 in the hope that ILU0 becomes a registered package.

Should be only merged after https://github.com/mcovalt/ILU0.jl/pull/3.

2020-10-19 21:57 UTC, dpo requested changes
Thanks! Could you please show the output of the examples?

2020-10-19 21:57 UTC, dpo commented on examples/test_diom.jl
> +opP = LinearOperator(Float64, N, N, false, false, y -> ldiv!(yP, F, y))
Let's factor out the problem setup, which is common to the two tests, to avoid duplication.

2020-10-20 15:03 UTC, amontoison commented
```julia
nnz(ILU) / nnz(A): 1.1e+00
[Without preconditioning] Residual norm:  4.7e-06
[Without preconditioning] Number of iterations: 239
[Split preconditioning] Residual norm:  3.6e-06
[Split preconditioning] Number of iterations:  62
[Left preconditioning] Residual norm:  4.2e-06
[Left preconditioning] Number of iterations:  62
[Right preconditioning] Residual norm:  3.3e-06
[Right preconditioning] Number of iterations:  62
```

2020-10-20 15:08 UTC, dpo commented
Thanks. With ILU0, don't we expect nnz(ILU) = nnz(A)?

2020-10-20 15:12 UTC, amontoison commented
I did the same remark myself yesterday and I suppose that the diagonal of `L` and `U` is not only composed of 1 (unlike Doolittle or Crout LU factorization) and the memory used for storing the diagonal of `A` is duplicate.

2020-10-20 15:21 UTC, amontoison commented
I was wrong, I did a mistake when I implemented `nnz` function.
https://github.com/mcovalt/ILU0.jl/pull/3/files#diff-3897f5bfe01078dd825e0c8199fc12d59f1248306a331ed9b5683c5163d5ed8dR220

2020-10-22 01:53 UTC, mcovalt reviewed
I've initiated package registration: https://github.com/JuliaRegistries/General/pull/23415#issuecomment-714010268

I made some modifications to the [ILUZero.jl](https://github.com/mcovalt/ILUZero.jl) package that this PR depends on. This review suggests changes I believe will work with these modifications. I've not tested this, however.

2020-10-22 01:53 UTC, mcovalt commented on examples/test_dqgmres.jl
> +using Krylov, LinearOperators, ILU0
```suggestion
using Krylov, LinearOperators, ILUZero
```

Package rename. See https://github.com/mcovalt/ILUZero.jl/commit/c4de1f0b5d405d917a13d85c75073f939429000a

2020-10-22 01:53 UTC, mcovalt commented on examples/test_dqgmres.jl
> +opN = LinearOperator(Float64, N, N, false, false, y -> backward_substitution(yN, F, y))
```suggestion
opM = LinearOperator(Float64, N, N, false, false, y -> forward_substitution!(yM, F, y))
opN = LinearOperator(Float64, N, N, false, false, y -> backward_substitution!(yN, F, y))
```

Function rename. See https://github.com/mcovalt/ILUZero.jl/commit/a32ddc54ea97328e55de5ea1e901301614ec10fb

2020-10-22 15:51 UTC, amontoison commented
Thanks @mcovalt !
I updated the examples and it works.
I tested with an other example, the discretization of a Poisson PDE in polar coordinates and the results are :
```
[Without preconditioning] Residual norm:  1.4e-06
[Without preconditioning] Number of iterations: 5000 (maximum number of iterations)
[Split preconditioning] Residual norm:  7.4e-09
[Split preconditioning] Number of iterations: 129
[Left preconditioning] Residual norm:  8.5e-08
[Left preconditioning] Number of iterations:  64
[Right preconditioning] Residual norm:  1.5e-08
[Right preconditioning] Number of iterations: 168
```

2020-10-22 15:57 UTC, dpo commented
Is nnz(L+U) = nnz(A) now?

2020-10-22 16:00 UTC, amontoison commented
Yes, I fixed it. https://github.com/mcovalt/ILUZero.jl/commit/01340a2f3909a0c3eb1eb81e5f0f76bf09fc4e8b
When ILUZero will be registered (in 3 days), I will add `ILUZero` in the `examples/Project.toml`.

2020-10-22 17:56 UTC, dpo commented
Great! Excellent work, guys!

2020-10-30 00:35 UTC, merged

2020-10-30 00:35 UTC, dpo commented
Thank you.