[BICGSTAB] Add a frequency option for the verbose mode
JuliaSmoothOptimizers/Krylov.jl pull request #237
Opened 2020-11-18 16:35 UTC by amontoison

2020-11-18 17:17 UTC, dpo commented
Just `frequency` is enough. Or `verbose` could be an int.

2020-11-18 17:29 UTC, amontoison commented
I like the second idea.
`verbose=0` -> no display
`verbose=p` with `p>=1` -> display at each multiple of p iterations

2020-11-18 17:31 UTC, dpo commented
Ok. Better say `verbose ≤ 0` -> no display.

2020-11-18 18:11 UTC, amontoison commented
I updated the PR.

2020-11-19 01:54 UTC, dpo requested changes

2020-11-19 01:54 UTC, dpo commented on src/bicgstab.jl
> +Additional details can be displayed if the verbose mode is enabled (verbose > 0).
```suggestion
Additional details can be displayed if verbose mode is enabled (verbose > 0).
```

2020-11-19 01:54 UTC, dpo commented on src/bicgstab.jl
> +The frequency of the display can be tuned, it is at each multiple of `verbose` iterations.
```suggestion
Information will be displayed every `verbose` iterations.
```

2020-11-19 13:21 UTC, merged

2020-11-19 13:21 UTC, dpo commented
Thank you.