in-place minres
JuliaSmoothOptimizers/Krylov.jl pull request #269
Opened 2021-03-15 21:13 UTC by geoffroyleconte

@amontoison

2021-03-15 21:40 UTC, amontoison requested changes
Great PR !!!

2021-03-15 21:40 UTC, amontoison commented on src/krylov_solvers.jl
> +abstract type KrylovSolver{S, T} end
```suggestion
abstract type KrylovSolver{S} end
```

2021-03-15 21:40 UTC, amontoison commented on src/krylov_solvers.jl
> +    solver = MinresSolver(b :: AbstractVector{T}, window :: Int=5) where T <: AbstractFloat
```suggestion
    solver = MinresSolver(A, b)
```

2021-03-15 21:40 UTC, amontoison commented on src/krylov_solvers.jl
> +- err_vec
```suggestion
- x
- r1
- r2
- w1
- w2
```

2021-03-15 21:40 UTC, amontoison commented on src/krylov_solvers.jl
> +end
```suggestion
mutable struct MinresSolver{S} <: KrylovSolver{S}
  x       :: S
  r1      :: S
  r2      :: S
  w1      :: S 
  w2      :: S
end
```

2021-03-15 21:40 UTC, amontoison commented on src/krylov_solvers.jl
> +end
```suggestion
function MinresSolver(A, b)
  m, n = size(A)
  S = typeof(b)
  return MinresSolver{S}(S(undef, n), S(undef, n), S(undef, n), S(undef, n), S(undef, n))
end
```

2021-03-15 21:40 UTC, amontoison commented on src/minres.jl
> +where `solver` is a [`Krylov.MinresSolver`](@ref) used to store the vectors used by `minres!`.
```suggestion
    (x, stats) = minres!(A, b :: AbstractVector{T}, solver :: MinresSolver{S};
                         M=opEye(), λ :: T=zero(T), atol :: T=√eps(T)/100,
                         rtol :: T=√eps(T)/100, etol :: T=√eps(T),
                         itmax :: Int=0, conlim :: T=1/√eps(T),
                         verbose :: Int=0) where {S, T <: AbstractFloat}

where `solver` is a [`Krylov.MinresSolver`](@ref) used to store the vectors used by `minres!`.
```

2021-03-15 21:40 UTC, amontoison commented on src/minres.jl
> +  x .= 0
```suggestion
  x .= zero(T)
```

2021-03-15 21:40 UTC, amontoison commented on src/minres.jl
> +  err_vec .= 0
```suggestion
  err_vec .= zeros(T, window)
```

2021-03-15 21:40 UTC, amontoison commented on src/minres.jl
> +minres(A, b :: AbstractVector{T}; window :: Int=5, kwargs...) where T <: AbstractFloat = minres!(A, b, MinresSolver(b, window); kwargs...)
```suggestion
@inline minres(A, b :: AbstractVector{T}; kwargs...) where T <: AbstractFloat = minres!(A, b, MinresSolver(A, b); kwargs...)
```

2021-03-15 21:40 UTC, amontoison commented on src/minres.jl
> +                 verbose :: Int=0) where {S, T <: AbstractFloat}
```suggestion
function minres!(A, b :: AbstractVector{T}, solver :: MinresSolver{S};
                 M=opEye(), λ :: T=zero(T), atol :: T=√eps(T)/100,
                 rtol :: T=√eps(T)/100, etol :: T=√eps(T),
                 itmax :: Int=0, conlim :: T=1/√eps(T),
                 verbose :: Int=0) where {S, T <: AbstractFloat}
```

2021-03-15 21:42 UTC, amontoison commented
if you want to rebase : 
```
git remote add upstream https://github.com/JuliaSmoothOptimizers/Krylov.jl.git
git fetch upstream
git rebase upstream/master
git push -f
```

2021-03-16 00:53 UTC, amontoison commented
@geoffroyleconte You were right, we need both `S` and `T` for `KrylovSolver{S, T}`. For some methods we cannot avoid the storage of vectors on CPU (`DIOM`, `DQGMRES`, ...). We can keep `err_vec` after all for `minres` but we need to check at the beginning that `length(solver.err_vec) == windows`.

2021-03-16 01:48 UTC, amontoison approved these changes

2021-03-16 01:52 UTC, amontoison commented
@dpo It's fine for me. What do you think about it ?

2021-03-16 13:12 UTC, dpo requested changes

2021-03-16 13:12 UTC, dpo commented on src/krylov_solvers.jl
> +- w2
This doesn’t seem important/useful to document since the user is never supposed to touch this structure. I would remove lines 9-13 and add comments inside the struct to guide the developer.

2021-03-16 13:12 UTC, dpo commented on test/test_minres.jl
> +  @test(stats.solved)
It would be great to add a test showing that `minres!(A, b, solver)` does not allocate.

2021-03-16 15:17 UTC, geoffroyleconte commented on src/krylov_solvers.jl
> +- w2
The user may need to access `x` no? And maybe other parameters if we create the same struct for other Krylov solver?

2021-03-16 15:24 UTC, geoffroyleconte commented on test/test_minres.jl
> +  @test(stats.solved)
I think this is not possible yet because there are still allocs done with the Residuals and Aresiduals vectors (see https://github.com/JuliaSmoothOptimizers/Krylov.jl/pull/272) . Even after the PR there will still be allocs because we create empty vectors for Residuals and Aresiduals and we do not fill them.

2021-03-16 15:40 UTC, dpo commented
I think we need to separate cleanly the Minres storage from the stats structure. I think x should be in the stats structure so that the user never needs to look into the solver private storage. We should have an option to not accumulate the arrays of rNorms and ArNorms and be able to check that when that option is turned on, the solver doesn’t allocate.

2021-03-16 16:32 UTC, geoffroyleconte commented
If x is in the stats structure, we will need to add it in the arguments of minres! . Do you mean something like
```minres!(A, b, solver, x; ....)``` ?

2021-03-16 16:50 UTC, amontoison commented on src/krylov_solvers.jl
> +- w2
`x` is always returned by a Krylov method and it's already a pointer to a vector inside a `KrylovSolver`.

2021-03-16 17:29 UTC, amontoison commented
Can you rebase your branch Geoffroy ?

2021-03-16 17:42 UTC, amontoison commented
It's not possible to remove all the allocation because we have some pointers that must be stored but you can add a test here https://github.com/JuliaSmoothOptimizers/Krylov.jl/blob/master/test/test_alloc.jl#L45-L48
that check `@allocated minres!(solver, A, b) <= 1000)`

2021-03-16 18:00 UTC, dpo commented
Store the stats structure inside MinresSolver and x inside the stats. Then just return the stats instead of (x, stats).

If the operators are preallocated, it should be possible to remove all allocations.

2021-03-16 18:16 UTC, amontoison commented
@dpo It will break every code that use `Krylov.jl` and stats.rNorms and stats.ArNorms have a different length at each call of a Krylov method if `history = true`.
I don't think that it's a good idea.

2021-03-16 18:25 UTC, dpo commented
> It will break every code that use Krylov.jl

I don’t think so. If you want, you can return (stats.x, stats) for the time being. What will break? At any rate, that’s what version numbers are for. Overall I think it’s an improvement.

> stats.rNorms and stats.ArNorms have a different length at each call of a Krylov method if history = true.

I think the objective of this should be to remove allocations. What I’m saying is that if history = false and the operators preallocate, we should be able to have no allocations in the solver itself.

2021-03-17 18:45 UTC, geoffroyleconte commented
@dpo , with @amontoison we think that it might be wise to keep this PR as it is for now, and to focus on removing the Residuals and Aresiduals in another PR. The ultimate goal is, as you said, to remove all allocations with `minres!`, maybe in version 0.8 .

2021-03-17 18:54 UTC, amontoison commented
@dpo We should think about a generic `stats` for all solvers. It will also solve #166. 
Let's do it step by step.

2021-03-17 18:57 UTC, amontoison commented on src/minres.jl
> +    (x, stats) = minres!(A, b :: AbstractVector{T}, solver :: MinresSolver{S, T};
```suggestion
    (x, stats) = minres!(solver :: MinresSolver{S, T}, A, b :: AbstractVector{T};
```

2021-03-17 20:40 UTC, dpo commented
> We should think about a generic stats for all solvers.

That’s a different topic. We’re just doing this for MINRES for now. Generic stats can come later (maybe).

2021-03-17 21:13 UTC, amontoison commented
> > We should think about a generic stats for all solvers.
> 
> That’s a different topic. We’re just doing this for MINRES for now. Generic stats can come later (maybe).

Yes, sure. But if you want to add `x` in `stats` like you asked, Geoffroy needs to update `SimpleStats` (which require to update all the other methods that use it) or create a new `stats` object and implement its `show` function.
We should discuss about it together friday.

2021-03-17 21:16 UTC, dpo commented
Sure, let’s duplicate SimpleStats to make one just for MINRES for now. This is our proof of concept. It’s not that difficult. No need to implement show at this point. The main point is: can we get rid of all allocations in the second call?

2021-03-17 21:17 UTC, amontoison commented
@geoffroyleconte 
We need to add `minres!` here : https://github.com/JuliaSmoothOptimizers/Krylov.jl/blob/master/src/variants.jl#L57-L65

2021-03-17 21:18 UTC, amontoison commented
> Sure, let’s duplicate SimpleStats to make one just for MINRES for now. This is our proof of concept. It’s not that difficult. No need to implement show at this point. The main point is: can we get rid of all allocations in the second call?

Yes, it will be the case for MINRES (and all methods that do not require A').

2021-03-17 21:51 UTC, dpo commented
Let’s do it so @geoffroyleconte can use it in his code.

2021-03-17 23:13 UTC, amontoison commented
@geoffroyleconte
You can continue without me.

2021-03-17 23:16 UTC, amontoison commented on test/test_alloc.jl
> +@test inplace_minres_bytes == 240
@dpo @geoffroyleconte 
The last allocation is the `KrylovStats`.

2021-03-18 00:18 UTC, dpo commented on test/test_alloc.jl
> +@test inplace_minres_bytes == 240
240 bytes!!! Much better!!! Thanks guys. Conclusion: anything is possible.

Let’s see if we can get to zero by putting the `SimpleStats` inside `MinresSolver`, and `x` inside `SimpleStats` (define a copy `MinresStats` of `SimpleStats` that also contains an `x`).

2021-03-18 19:10 UTC, geoffroyleconte commented on test/test_alloc.jl
> +@test inplace_minres_bytes == 32
I am now down to 32 bytes but it seems I cannot go lower

2021-03-18 19:23 UTC, amontoison commented on test/test_alloc.jl
> +@test inplace_minres_bytes == 32
Comment this part of code https://github.com/JuliaSmoothOptimizers/Krylov.jl/pull/269/files/ac17b26c9081c7a7fb3168452aeca9976c41e679..98caea1db74a85ec478f6f9ec4dbea26a08df282#diff-af32b9d734e2fe1b702cc5c0d7fc714c5c978e2ee4fc0bfb449a68d837b63453R67-R80 to see if the 32 bytes comes from the `wrap_preconditioners` function.

2021-03-18 19:29 UTC, amontoison commented
A last issue that we have is how to reuse the vector preallocated by `PreallocatedLinearOperator`.
The only easy solution that I see is stored the `y` in the `MinresSolver` and use `mul!(y, A, v)`.
https://github.com/JuliaSmoothOptimizers/Krylov.jl/blob/master/src/minres.jl#L133

Otherwise Geoffroy will need to create a new `PreallocatedLinearOperator` (which allocates 1 vector) at each iteration of its IPM method.

2021-03-18 20:06 UTC, dpo commented
Couldn't he simply preallocate a vector before his main loop and create a new PreallocatedLinearOperator inside the loop that uses that vector as storage?

2021-03-18 20:45 UTC, geoffroyleconte commented on test/test_alloc.jl
> +@test inplace_minres_bytes == 32
If you mean to comment L67-L81 of variants.jl, it does not remove the 32 bytes

2021-03-18 20:51 UTC, amontoison commented
> Couldn't he simply preallocate a vector before his main loop and create a new PreallocatedLinearOperator inside the loop that uses that vector as storage?

You're right, I forgot that we have that kind of constructor : https://github.com/JuliaSmoothOptimizers/LinearOperators.jl/blob/master/src/PreallocatedLinearOperators.jl#L82

2021-03-18 20:58 UTC, geoffroyleconte commented
Could we replace `*` from LinearOperators by `mul!` ? This way we would not have to create every time a new LinearOperator if `A` is a matrix.

2021-03-18 21:29 UTC, dpo commented
@geoffroyleconte That's a great idea and we've discussed that in the past. I think LinearOperators could use some attention and be based on `mul!()`. @amontoison Didn't you concoct a proof of concept at some point?

2021-03-18 21:41 UTC, geoffroyleconte commented
There is nothing to change in LinearOperators for this I think. If `A` is a matrix then `MinresSolver` preallocates 1 vector, and `minres!` uses the normal `mul!` . Otherwise, it uses this function: https://github.com/JuliaSmoothOptimizers/LinearOperators.jl/blob/ea38e7539ab036e748f126b98a2c0076131a798c/src/operations.jl#L20 and stores the preallocated vector by the `PreallocatedLinearOperator` in `MinresSolver` . 
The only issue is if `A` is a LinearOperator without allocation (like OpEye), but maybe we can find something to make it work?

2021-03-18 21:41 UTC, amontoison commented
Yes, I did a macro such that `@.. y = A * x` dispatch to `mul!(y,  A, x)` but the main problem was the implementation of `mul!` in `LinearOperators`.

2021-03-19 01:48 UTC, geoffroyleconte commented
This PR is getting more complicated than it should be. I think `minres!` should not force the user to work with a `LinearOperator{T}` , maybe even the whole package. It should also be able to work with an `AbstractMatrix{T}` as input, and use the  `mul!` function from LinearAlgebra. 
I suggest we modify this PR so that `minres!` works with `AbstractMatrix{T}` as input (otherwise I will have to write my own `minres!` function and add it to RipQP because I do not need LinearOperators for now). Then we pause it, and make some modifications to LinearOperators to implement the `mul!` function and deal with allocations issues.
This way, we would have a `minres!` function that takes any `AbstractMatrix{T}` or `LinearOperator{T}` as input, and would only specialise when using `mul!`.

2021-03-19 22:09 UTC, dpo commented on src/krylov_solvers.jl
> +  opA = typeof(A) <: AbstractMatrix ? PreallocatedLinearOperator(A, storagetype=S, symmetric=true) : A
you don't want to do that because you want to be able to call `minres!()` later with a different operator and a different `b` that have the same dimensions.

2021-03-19 23:22 UTC, dpo commented on src/krylov_solvers.jl
> +  x  = S(undef, n)
I think this should be `x = similar(b, n)` because it could result in an error:
```julia
julia> b1 = rand(10); b = view(b1, 1:2:10)
julia> S = typeof(b)
SubArray{Float64,1,Array{Float64,1},Tuple{StepRange{Int64,Int64}},true}

julia> S(undef, 5)
ERROR: MethodError: no method matching SubArray{Float64,1,Array{Float64,1},Tuple{StepRange{Int64,Int64}},true}(::UndefInitializer, ::Int64)
Closest candidates are:
  SubArray{Float64,1,Array{Float64,1},Tuple{StepRange{Int64,Int64}},true}(::Any, ::Any, ::Any, ::Any) where {T, N, P, I, L} at subarray.jl:19
```

2021-03-20 01:08 UTC, amontoison requested changes

2021-03-20 01:08 UTC, amontoison commented on src/krylov_solvers.jl
> +function MinresSolver(opA :: PreallocatedLinearOperator{T}, b :: AbstractVector{T}; window :: Int=5) where T <: AbstractFloat
If someone wants to use `LinearMaps` or its own linear operator it should be able to do it. It's for that reason that we removed the type restrictions on `A` , `M` and `N` for all methods.

2021-03-20 01:08 UTC, amontoison commented on src/krylov_solvers.jl
> +  m, n = opA.nrow, opA.ncol
Keep the generic `m, n = size(A)`

2021-03-20 01:09 UTC, amontoison commented on src/krylov_solvers.jl
> +function MinresSolver(opA :: PreallocatedLinearOperator{T}, b :: AbstractVector{T}; window :: Int=5) where T <: AbstractFloat
```suggestion
function MinresSolver(A, b :: AbstractVector{T}; window :: Int=5) where T <: AbstractFloat
```

2021-03-20 01:20 UTC, amontoison commented
I like this implementation. It will break nothing !

2021-03-20 01:21 UTC, amontoison commented on src/krylov_solvers.jl
> +    opA, solver = MinresSolver(A, b :: AbstractVector{T}; window :: Int=5) where T <: AbstractFloat
```suggestion
    solver = MinresSolver(A, b :: AbstractVector{T}; window :: Int=5) where T <: AbstractFloat
```

2021-03-20 03:00 UTC, dpo requested changes

2021-03-20 03:02 UTC, dpo commented on test/test_alloc.jl
> +@test inplace_minres_bytes == 32
https://docs.julialang.org/en/v1/manual/profile/#Memory-allocation-analysis

2021-03-22 19:13 UTC, geoffroyleconte commented on src/krylov_solvers.jl
> +function MinresSolver(opA :: PreallocatedLinearOperator{T}, b :: AbstractVector{T}; window :: Int=5) where T <: AbstractFloat
OK, but in this case it shall be expected that the user does not give an `AbstractMatrix` to `MinresSolver`.

2021-03-22 19:16 UTC, amontoison commented on src/krylov_solvers.jl
> +function MinresSolver(opA :: PreallocatedLinearOperator{T}, b :: AbstractVector{T}; window :: Int=5) where T <: AbstractFloat
Why ?

2021-03-22 19:37 UTC, geoffroyleconte commented on src/krylov_solvers.jl
> +function MinresSolver(opA :: PreallocatedLinearOperator{T}, b :: AbstractVector{T}; window :: Int=5) where T <: AbstractFloat
Sorry for `minres!` I should say, otherwise the vectors created by the `PreallocatedLinearOperator` cannot be reused when using `minres!` multiple times

2021-03-22 19:50 UTC, amontoison commented on src/krylov_solvers.jl
> +function MinresSolver(opA :: PreallocatedLinearOperator{T}, b :: AbstractVector{T}; window :: Int=5) where T <: AbstractFloat
Yes you're right, but it's the problem of the user in that case.

2021-03-22 19:55 UTC, dpo commented on src/krylov_solvers.jl
> +function MinresSolver(opA :: PreallocatedLinearOperator{T}, b :: AbstractVector{T}; window :: Int=5) where T <: AbstractFloat
Exactly. It's the user's responsibility (at least for now).

2021-03-29 13:27 UTC, amontoison commented
I found the culprit, Julia cannot interfered the type of a `MinresSolver` when allocation tests are performed in the REPL. To avoid this issue I wrapped the tests in a function `test_alloc()`.

2021-03-29 13:56 UTC, dpo commented
Thank you. Tests should always be in functions It seems like it isn’t working with Julia 1.3 though.

2021-03-29 14:27 UTC, geoffroyleconte commented
Thank you! Should we upgrade the Julia compat?

2021-03-29 14:50 UTC, amontoison commented
I think that I can help a little bit Julia 1.3 and type inference. I will have a look ASAP.

2021-04-06 04:19 UTC, amontoison commented
![allocs](https://user-images.githubusercontent.com/35051714/113657628-53b5f480-966c-11eb-9590-5a62c96a3dc3.png)

We cannot remove the 32 bits with Julia < 1.5. I propose to update the allocation test like this https://github.com/JuliaSmoothOptimizers/Krylov.jl/pull/280/files#diff-8da4f5f3a63cefac6bb5115d0b873b95246ef210751fb7a8269141807e98870dR141

I can rebase the PR tomorrow if it's fine for you. I also found some minor issues if `history=true` with the last commits of Geoffroy. I can solve it in the same time.

2021-04-06 14:31 UTC, geoffroyleconte commented
It is fine for me, thank you!

2021-04-06 15:04 UTC, dpo commented
Instead of zero bytes, I suggest measuring the amount allocated with Julia 1.5 and using that as the benchmark (after making sure it matches the "theory").

2021-04-06 21:07 UTC, geoffroyleconte commented
@dpo I don't understand

2021-04-06 22:17 UTC, dpo commented
I was replying to @amontoison’s proposal.

2021-04-06 22:28 UTC, amontoison commented
> Instead of zero bytes, I suggest measuring the amount allocated with Julia 1.5 and using that as the benchmark (after making sure it matches the "theory").

I'm sure to understand the differences with what I proposed and I did for BICGSTAB ? 
https://github.com/JuliaSmoothOptimizers/Krylov.jl/pull/280/files#diff-8da4f5f3a63cefac6bb5115d0b873b95246ef210751fb7a8269141807e98870dR129-R141

2021-04-07 19:13 UTC, geoffroyleconte commented
@dpo @amontoison can we merge this if I check that the Julia version is 1.5 for the allocs test with `minres!` ? It is very inconvenient to have to rebase every time... We can open an issue to make allocs tests for other versions later.

2021-04-07 19:58 UTC, dpo commented
> I don't understand. What are the differences with what I proposed and I did for BICGSTAB ?

I didn’t realize that you simply deactivated the test for Julia ≤ 1.5. That’s ok I guess.

2021-04-07 20:05 UTC, dpo commented
Also it looks like the coverage went down. I think we just need to call the variants in the tests: A = dense matrix, b = sparse vector, etc.

2021-04-07 20:05 UTC, dpo commented
@geoffroyleconte Could you deactivate the MINRES allocation test for Julia ≤ 1.5 as @amontoison did? The tests should pass with Julia 1.3.

2021-04-08 18:06 UTC, dpo commented on test/test_variants.jl
> +                @eval $fn($solver, $adjoint($A), $b)
See the annotations in `variants.jl` to see which are not covered by the current tests.

2021-04-08 18:27 UTC, geoffroyleconte commented on test/test_variants.jl
> +                @eval $fn($solver, $adjoint($A), $b)
There is an issue when `b` is a `SparseVector`, I did not find how to fix it. But anyway the function converts `b`to a `Vector` so this is not really an issue, the user just has to give a `Vector`instead of a `SparseVector`. All these issues will be fixed when we change LinearOperators

2021-04-08 18:30 UTC, dpo commented on test/test_variants.jl
> +                @eval $fn($solver, $adjoint($A), $b)
I understand, but what we’re trying to fix now is coverage. What’s the problem with SparseVector?

2021-04-08 22:41 UTC, dpo commented on test/test_variants.jl
> +                @eval $fn($solver, $adjoint($A), $b)
Coverage is completely separate from the in-place solver. We need to test the variants simply to ensure that they are callable and behave correctly. It's understood that they will allocate. But allocations are not what we're testing. If you're having an issue with `SparseVector`s, then it's an indication that there's a bug and we should fix it.

Could you paste the error here?

2021-04-08 22:51 UTC, geoffroyleconte commented on test/test_variants.jl
> +                @eval $fn($solver, $adjoint($A), $b)
There is no issue with `minres`, only with `minres!`. It looks like the coverage is increased. We are loosing time on minor issues that will be fixed with the changes that will be made on LinearOperators.jl. We should say that for now the user has to use PreallocatedLinearOperators. It is actually the only way he can avoid allocations with the current implementation. I can add this to the documentation if needed.

Here is the error:

`minres! ERROR: LoadError: LoadError: TypeError: in typeassert, expected SparseVector{Float32,Int32}, got a value of type Array{Float32,1}
Stacktrace:
 [1] *(::PreallocatedLinearOperator{Float32}, ::SparseVector{Float32,Int32}) at C:\Users\Geoffroy Leconte\.julia\packages\LinearOperators\qFko7\src\operations.jl:7
 [2] minres!(::MinresSolver{Float32,SparseVector{Float32,Int32}}, ::PreallocatedLinearOperator{Float32}, ::Array{Float32,1}; M::opEye, λ::Float32, atol::Float32, rtol::Float32, ratol`

2021-04-09 14:18 UTC, geoffroyleconte commented
I added annotations so that the user is forced to use `PreallocatedLinearOperators` with `minres!`. 

I can raise an issue to deal with `b` when it is a `SparseVector`. This may be solved with https://github.com/JuliaSmoothOptimizers/LinearOperators.jl/pull/172 , but if it works it will change all the Krylov variants with `b::SparseVector{T}` so we should deal with this in another PR.

2021-04-09 14:19 UTC, amontoison commented on src/krylov_solvers.jl
> +function MinresSolver(A :: PreallocatedLinearOperator{T}, b :: Vector{T}; window :: Int=5) where T <: AbstractFloat
We cannot use anymore `minres` on GPU :(

2021-04-09 14:28 UTC, dpo commented on src/krylov_solvers.jl
> +function MinresSolver(A :: PreallocatedLinearOperator{T}, b :: Vector{T}; window :: Int=5) where T <: AbstractFloat
I thought the annotation should go in `minres!()`, not here. Would that also break the GPU?

2021-04-09 14:41 UTC, amontoison commented on src/krylov_solvers.jl
> +function MinresSolver(A :: PreallocatedLinearOperator{T}, b :: Vector{T}; window :: Int=5) where T <: AbstractFloat
`b` must be an `AbstractVector{T}` to keep support with `CuVector{T}`. (GPU storage).
The parametrization of A is not needed too : https://juliasmoothoptimizers.github.io/Krylov.jl/dev/matrix-free/

But one thing should be explained somewhere, if the user want to use `minres!`, he should wrap itselft A::AbstractMatrix in a PreallocatedLinearOperator. It's only done automatically with `minres`.
If the user already uses its linear operator (`LinearOperators.jl`, `LinearMaps.jl`, ...) he don't need to do anything.

2021-04-09 14:43 UTC, geoffroyleconte commented on src/krylov_solvers.jl
> +function MinresSolver(A :: PreallocatedLinearOperator{T}, b :: Vector{T}; window :: Int=5) where T <: AbstractFloat
OK, I removed annotations and documented that the user has to use PreallocatedLinearOperators to avoid allocations.

2021-04-09 14:45 UTC, amontoison approved these changes

2021-04-09 18:17 UTC, merged

2021-04-09 18:17 UTC, dpo commented
Great! Thank you!