[GPMR] Support of complex numbers
JuliaSmoothOptimizers/Krylov.jl pull request #483
Opened 2022-01-20 17:11 UTC by amontoison

I need #481 to add tests with complex numbers.

2022-01-22 00:18 UTC, amontoison commented on src/gpmr.jl
> +  rNorm = sqrt(abs(γ)^2 + abs(β)^2)
```suggestion
  # Compute ‖r₀‖² = γ² + β²
  rNorm = sqrt(γ^2 + β^2)
```

2022-01-22 00:19 UTC, amontoison commented on src/gpmr.jl
> +  rNorm = sqrt(abs(γ)^2 + abs(β)^2)
I forgot that `γ` and `β` are real numbers...

2022-04-05 23:33 UTC, dpo requested changes

2022-04-05 23:33 UTC, dpo commented on src/gpmr.jl
>      # Rₖ can be singular is the system is inconsistent
```suggestion
    # Rₖ can be singular if the system is inconsistent
```

2022-04-05 23:41 UTC, amontoison commented on src/gpmr.jl
>      # Rₖ can be singular is the system is inconsistent
Thanks !
It's already fixed on the `main` branch (https://github.com/JuliaSmoothOptimizers/Krylov.jl/blob/main/src/gpmr.jl#L404).
The mistake will be removed after the rebase.

2022-04-05 23:50 UTC, merged