Fix sqrt CR
JuliaSmoothOptimizers/Krylov.jl pull request #527
Opened 2022-02-07 16:25 UTC by geoffroyleconte

Hi, I have numerical issues with CR used with RipQP:
https://github.com/JuliaSmoothOptimizers/RipQP.jl/pull/139
I think this PR should fix my issues, but I can't be sure because the tests only fail with MacOS.

2022-02-07 17:08 UTC, dpo commented on src/cr.jl
> +    pNorm = (pNorm² < zero(T)) ? zero(T) : sqrt(pNorm²)
That's interesting. It must be an instability in the recursion formula for ‖p‖². For years, I've been wondering if that could be an issue but we never hit an example. So thank you!

For now, please only set `pNorm` to zero if `abs(pNorm^)` is very, very small. Otherwise, it would be a math bug.

2022-02-07 17:32 UTC, amontoison commented on src/cr.jl
> +    pNorm = (pNorm² < zero(T)) ? zero(T) : sqrt(pNorm²)
```suggestion
    pNorm = (pNorm² < eps(T)) ? zero(T) : sqrt(pNorm²)
```

2022-02-07 18:42 UTC, dpo commented on src/cr.jl
> +    pNorm = (pNorm² < zero(T)) ? zero(T) : sqrt(pNorm²)
I guess. We have to keep in mind that it's a patch. It would be great to add a comment in the code with a `TODO` or `FIXME`.

2022-02-07 19:57 UTC, geoffroyleconte commented on src/cr.jl
> +    pNorm = (pNorm² < zero(T)) ? zero(T) : sqrt(pNorm²)
Here is the error:
 ```
DomainError with -6.841306819148919e-16:
  sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).
```
The only issue is when `pNorm < 0`. What do you want me to change?

2022-02-07 20:53 UTC, geoffroyleconte commented on src/cr.jl
> +    pNorm = (pNorm² < zero(T)) ? zero(T) : sqrt(pNorm²)
@dpo I don't understand. The value I get is negative so it's smaller than `0` and `eps(T)`

2022-02-07 22:41 UTC, dpo commented on src/cr.jl
> +    pNorm = (pNorm² < zero(T)) ? zero(T) : sqrt(pNorm²)
It should be smaller in absolute value.

2022-02-09 00:33 UTC, dpo commented on src/cr.jl
> +      error("cr encountered numerical issues")
Instead of just crashing, you could exit the solver with an error status.

2022-02-09 01:55 UTC, geoffroyleconte commented
Are the JSOSolvers.jl test failures due to this PR? The error for the "latest" version mentions CG

2022-02-09 13:24 UTC, dpo requested changes
Almost there.

2022-02-09 13:24 UTC, dpo commented on src/cr.jl
> +      stats.status = "solver incountered numerical issues"
```suggestion
      stats.status = "solver encountered numerical issues"
```

2022-02-09 15:26 UTC, dpo approved these changes

2022-02-09 16:31 UTC, merged