Add default value `memory` in `KrylovSolver`
JuliaSmoothOptimizers/Krylov.jl pull request #545
Opened 2022-02-28 15:54 UTC by tmigot

Connected to https://github.com/JuliaSmoothOptimizers/LLSModels.jl/pull/35

2022-02-28 18:00 UTC, dpo requested changes

2022-02-28 18:31 UTC, tmigot commented on src/krylov_solvers.jl
> +  function DqgmresSolver(A, b, memory = 20)
Thanks for the review. Should I do the same for the 4 solvers?

Should I also change the default parameter in the functions ?https://github.com/JuliaSmoothOptimizers/Krylov.jl/blob/6d28d54aaeda21857a6f6c871686b3eb7cc95f65/src/diom.jl#L38

2022-02-28 19:04 UTC, dpo commented on src/krylov_solvers.jl
> +  function DqgmresSolver(A, b, memory = 20)
> Thanks for the review. Should I do the same for the 4 solvers?

Yes, please.

> Should I also change the default parameter in the functions ?

Yes I think so. @amontoison ?

2022-02-28 19:18 UTC, geoffroyleconte commented
Hi, thanks I will also benefit from this change! Can you do it for GPMR as well please? And maybe inform the user of the default values in the doc?

2022-02-28 19:29 UTC, amontoison commented on src/krylov_solvers.jl
> +  function DqgmresSolver(A, b, memory = 20)
I propose to directly add `memory = min(20, n)` [here](https://github.com/JuliaSmoothOptimizers/Krylov.jl/blob/main/src/krylov_solvers.jl#L34) by default.

2022-02-28 19:34 UTC, amontoison commented on src/krylov_solvers.jl
> +  function DqgmresSolver(A, b, memory = 20)
We just need to explain that `memory` cannot exceed the size of the linear systems.

2022-02-28 19:37 UTC, amontoison commented on src/krylov_solvers.jl
> +  function DqgmresSolver(A, b, memory = 20)
It's relevant if we solve small systems (size < 20) but it's also a safeguard if the user gives an inappropriate value.

2022-02-28 22:49 UTC, amontoison approved these changes

2022-03-01 14:32 UTC, dpo requested changes

2022-03-01 14:32 UTC, dpo commented on src/krylov_solvers.jl
> +`memory` is set to `n` if the given value is larger than `n`.
```suggestion
`memory` is set to `n` if the value given is larger than `n`.
```

2022-03-01 15:43 UTC, geoffroyleconte approved these changes

2022-03-01 15:51 UTC, merged

2022-03-01 15:51 UTC, dpo commented
Thank you.