[MINRES] Move restart option to MinresSolver
JuliaSmoothOptimizers/Krylov.jl pull request #562
Opened 2022-04-21 22:56 UTC by geoffroyleconte

I found the use of the restart option not convenient to write generic code. Also the fact that the `restart` parameter was in the arguments of the function was misleading because it was not possible to restart `minres` (the not in-place version) (correct me if I'm wrong).

I added a function `warm_start!(solver, x0)` that is used to tell MINRES to solve the problem from x0. 
`MinresSolver` has now an attribute `restart` set to false by default. When using `warm_start!`, it is set to true. After `minres!` is called, it is set to false again.

If we agree to merge with, we could do the same for all other Krylov solvers by adding a method to the `warm_start!` function.

2022-04-21 23:21 UTC, dpo commented
The use of the word "restart" is very confusing here and we should remove it. There is no restarting MINRES because it's based on a 3-term recurrence. The use of "restart" is reserved for methods based on the Arnoldi process (FOM, GMRES, and now, GPMR). We should simply be able to pass an initial guess to `solve!()` and what you're doing in `warm_start!()` should happen.

2022-04-22 00:27 UTC, geoffroyleconte commented
@dpo I don't think that `x0` should be provided when calling `minres!`. I find it easier to specify `x0` in the `MinresSolver` to write generic code with different Krylov Methods. 
Also after discussing with @amontoison some methods such as GPMR would require in the warm start process the inverse of the diagonal block (`M` and `N` when we require `inv(M)` and `inv(N)`).
Should i change the `restart` boolean attribute of `MinresSolver` to `warm_start`?

2022-04-22 16:07 UTC, dpo commented
In my opinion, `x0` is not related to the solver, but to the solve. The role of the solver object is to preallocate memory. However, we should be able to perform several solves with the same solver object, for example with different right-hand sides or different initial guesses.

2022-04-22 17:29 UTC, geoffroyleconte commented
But in this case, what should be the default value of `x0`? `nothing`? Because if we set it to a vector of zeros we allocate a vector at each `minres!` call.
An other advantage of `warm_start!` is that it removes the `Δx` allocation from `minres!` (I just changed this in my last commit because I forgot to remove it).

2022-04-22 23:01 UTC, dpo commented on test/test_minres.jl
> +      (x, stats) = minres(A, b, solver.x)
Are you restarting it from the solution? Why not run the first solve with relaxed tolerances? Otherwise I supposed the second solve doesn't perform any iterations at all?!

2022-04-23 00:56 UTC, geoffroyleconte commented on test/test_minres.jl
> +      (x, stats) = minres(A, b, solver.x)
I think the tests are the same, `minres(A, b, solver.x)` creates internally a new `MinresSolver` that is different from `solver`

2022-04-23 16:19 UTC, dpo commented on test/test_minres.jl
> +      (x, stats) = minres(A, b, solver.x)
but isn't it starting from the solution?

2022-04-24 01:48 UTC, geoffroyleconte commented on test/test_minres.jl
> +      (x, stats) = minres(A, b, solver.x)
Oh yes my bad I forgot to add `itmax = 50`

2022-04-24 02:05 UTC, dpo approved these changes
ok great, thank you!

2022-04-24 03:27 UTC, amontoison requested changes
Geoffroy, is it ok to keep the same type for `b` and `x0` ?
I would like to avoid overparameterization.
If you want to `warm_start` from a solution with a different precision,
you will still be able to use the `warm_start!` function.

2022-04-24 03:27 UTC, amontoison commented on src/minres.jl
> +  warm_start = solver.warm_start
Can you move this line in the section `# Set up workspace.` ?

2022-04-24 03:27 UTC, amontoison commented on src/minres.jl
> +function minres(A, b :: AbstractVector{FC}, x0 :: AbstractVector{FC0}; window :: Int=5, kwargs...) where {FC <: FloatOrComplex, FC0 <: FloatOrComplex}
```suggestion
function minres(A, b :: AbstractVector{FC}, x0 :: AbstractVector{FC}; window :: Int=5, kwargs...) where {FC <: FloatOrComplex}
```

2022-04-24 03:27 UTC, amontoison commented on src/minres.jl
> +function minres!(solver :: MinresSolver{T,FC,S}, A, b :: AbstractVector{FC}, x0::AbstractVector{FC0};
```suggestion
function minres!(solver :: MinresSolver{T,FC,S}, A, b :: AbstractVector{FC}, x0::AbstractVector{FC};
```

2022-04-24 03:27 UTC, amontoison commented on src/minres.jl
> +                 kwargs...) where {T <: AbstractFloat, FC <: FloatOrComplex{T}, S <: DenseVector{FC}, FC0 <: FloatOrComplex}
```suggestion
                 kwargs...) where {T <: AbstractFloat, FC <: FloatOrComplex{T}, S <: DenseVector{FC}}
```

2022-04-24 03:27 UTC, amontoison commented on src/minres.jl
> +                 kwargs...) where {T <: AbstractFloat, FC <: FloatOrComplex{T}, S <: DenseVector{FC}, FC0 <: FloatOrComplex}
Can you write lines 333-334 on the same one?

2022-04-24 03:27 UTC, amontoison commented on test/test_minres.jl
> +      (x, stats) = minres(A, b, solver.x)
Yes, It only gives an approximate solution after `itmax = 50` iterations.

2022-04-24 03:48 UTC, amontoison commented
I like the current solution because we now have the warm start for the non-inplace method and `x0` can be given for the solve (`minres(A, b, x0)` and `minres!(solver, A, b, x0)`.
The previous implementation was not user-friendly (solver.x = x0) and it's also great that we can remove the misleading `restart` kwarg.

@dpo You are right that `x0` should not be related to the solver but if we want to have the same code of MINRES working for both methods (`minres(A,b)` and `minres(A, b, x0)`), you should add `warm_start` attribute in the solver and store the initial guess in the solver.

2022-04-24 04:06 UTC, dpo commented
It's ok to store x0 in the solver. I just didn't agree that it should be passed to the solver constructor.

2022-04-24 16:01 UTC, geoffroyleconte commented on src/minres.jl
> +function minres!(solver :: MinresSolver{T,FC,S}, A, b :: AbstractVector{FC}, x0::AbstractVector{FC0};
I'm not sure it is a good idea. If the user has an approximate solution in `Float32` and wants to refine the system in `Float64` he would have to allocate one more vector. I can change it to `x0::AbstractVector` if this is really an issue, but what's the problem with adding one more type parameter?

2022-04-24 18:28 UTC, amontoison commented on src/minres.jl
> +function minres!(solver :: MinresSolver{T,FC,S}, A, b :: AbstractVector{FC}, x0::AbstractVector{FC0};
If you add one more type parameter you will compile a new version of `minres` / `minres!` specialized for `FC0`.
We only need one method for all type of `x0`.

2022-04-24 18:32 UTC, amontoison commented
We have another issue Geoffroy, if the user provide `x0` in `minres` or `minres!`, `\Delta x` is not needed anymore to store the previous solution except if `x0 == solver.x`. It should be possible to do `solver.x .+= x0` at the end of the method.

2022-04-24 21:06 UTC, amontoison approved these changes

2022-04-24 21:11 UTC, merged