Update warm start documentation
JuliaSmoothOptimizers/Krylov.jl pull request #577
Opened 2022-05-04 16:48 UTC by geoffroyleconte

2022-05-04 17:29 UTC, dpo requested changes

2022-05-04 17:29 UTC, dpo commented on docs/src/warm_start.md
> +Most Krylov methods in this module can use a starting point that might be closer from a solution.
```suggestion
Most Krylov methods in this module accept a starting point as argument. The starting point is used as initial approximation to a solution.
```

2022-05-04 17:29 UTC, dpo commented on docs/src/warm_start.md
> +If the user has an initial guess `x0`, it can be also provided directly.
```suggestion
If the user has an initial guess `x0`, it can be provided directly.
```

2022-05-04 17:29 UTC, dpo commented on docs/src/warm_start.md
> +It is also possible to use the `warm_start!` function directly on the solver.
```suggestion
It is also possible to use the `warm_start!` function to feed the starting point into the solver.
```

2022-05-04 17:29 UTC, dpo commented on docs/src/warm_start.md
> +# these two lines are equivalent to cg!(solver, A, b, x0)
```suggestion
# the previous two lines are equivalent to cg!(solver, A, b, x0)
```

2022-05-04 17:29 UTC, dpo commented on docs/src/warm_start.md
> +Explicit restarts cannot be avoided with some block methods such as TRIMR due to the preconditioners.
```suggestion
Explicit restarts cannot be avoided in certain block methods, such as TRIMR, due to the preconditioners.
```

2022-05-04 17:29 UTC, dpo commented on docs/src/warm_start.md
> +In this section, we present how GMRES(k) and FOM(k) can be implemented thanks to the warm start.
```suggestion
In this section, we show how to use warm starts to implement GMRES(k) and FOM(k).
```

2022-05-04 17:29 UTC, dpo commented on docs/src/warm_start.md
> +  solve!(solver, A, b, x0, itmax=k)
where is x0 defined?

2022-05-04 18:35 UTC, amontoison requested changes

2022-05-04 18:35 UTC, amontoison commented on docs/src/warm_start.md
> +Explicit restarts cannot be avoided in certain block methods, such as TRIMR, due to the preconditioners.
```suggestion
Explicit restarts cannot be avoided in certain block methods, such as TriMR, due to the preconditioners.
```

2022-05-04 18:35 UTC, amontoison commented on docs/src/warm_start.md
> +If a Krylov method doesn't have the option to warm start, it can be still be done explicitly.
```suggestion
If a Krylov method doesn't have the option to warm start, it can still be done explicitly.
```

2022-05-04 18:35 UTC, amontoison commented on docs/src/warm_start.md
> +  cg!(solver, A, b, solver.x, itmax=100) # the 4th argument tells cg! to start from solver.x
```suggestion
  cg!(solver, A, b, solver.x, itmax=100) # cg! uses the approximate solution `solver.x` as starting point
```

2022-05-04 18:37 UTC, amontoison requested changes

2022-05-04 18:37 UTC, amontoison commented on docs/src/warm_start.md
>  x₀ = copy(solver.x)     # Ax₀ ≈ b
```suggestion
x₀ = solver.x           # Ax₀ ≈ b
```

2022-05-04 18:56 UTC, amontoison approved these changes

2022-05-05 01:16 UTC, dpo approved these changes

2022-05-05 01:16 UTC, dpo commented on docs/src/warm_start.md
> +  solve!(solver, A, b, solver.x, itmax=k)
Yes ok. That's what wasn't making any sense.

2022-05-05 15:29 UTC, merged

2022-05-05 15:29 UTC, amontoison commented
Thanks @geoffroyleconte!