New LSMR stats
JuliaSmoothOptimizers/Krylov.jl pull request #601
Opened 2022-07-20 18:38 UTC by AntoninKns

Adding new LSMR stats in order to retrieve more information without additional cost.

2022-07-20 19:15 UTC, amontoison approved these changes

2022-07-21 16:36 UTC, dpo requested changes
Great! Just a very minor comment.

2022-07-21 16:36 UTC, dpo commented on src/krylov_stats.jl
> +Type for statistics returned by LSMR, the attributes are:
```suggestion
Type for statistics returned by LSMR. The attributes are:
```

2022-07-21 18:12 UTC, dpo approved these changes

2022-07-21 18:24 UTC, merged