[documentation] Add a section about preconditioners
JuliaSmoothOptimizers/Krylov.jl pull request #609
Opened 2022-08-19 03:13 UTC by amontoison

close #222

2022-08-19 03:21 UTC, amontoison commented
https://juliasmoothoptimizers.github.io/Krylov.jl/previews/PR609/

2022-08-20 02:52 UTC, dpo reviewed
Here are a few comments that you could also apply to other sections.

2022-08-20 02:52 UTC, dpo commented on docs/src/preconditioners.md
> +The solvers in Krylov.jl support preconditioners that modify a given linear systems $Ax = b$ into a form that allows a faster convergence.
```suggestion
The solvers in Krylov.jl support preconditioners, i.e., transformations that modify a linear systems $Ax = b$ into an equivalent form that may yield faster convergence in finite-precision arithmetic.
```

2022-08-20 02:52 UTC, dpo commented on docs/src/preconditioners.md
> +It exists three variants of preconditioning:
```suggestion
There exist three variants of preconditioning:
```

2022-08-20 02:52 UTC, dpo commented on docs/src/preconditioners.md
> +| Left preconditioning | Two-sided preconditioning       | Right preconditioning          |
```suggestion
| Left preconditioning | Split preconditioning           | Right preconditioning          |
```

2022-08-20 02:52 UTC, dpo commented on docs/src/preconditioners.md
> +
```suggestion

where $M$ and $N$ are square and nonsingular.
```

2022-08-20 02:52 UTC, dpo commented on docs/src/preconditioners.md
> +We provide these preconditioners with the arguments `M` and `N`.
```suggestion
In our implementations, those preconditioners are specified via the arguments `M` and `N`.
```

2022-08-20 02:52 UTC, dpo commented on docs/src/preconditioners.md
> +A Krylov method dedicated to unsymmetric systems allows the three variants.
```suggestion
Methods concerned: [`CGS`](@ref cgs), [`BiCGSTAB`](@ref bicgstab), [`DQGMRES`](@ref dqgmres), [`GMRES`](@ref gmres), [`DIOM`](@ref diom) and [`FOM`](@ref fom).

A Krylov method dedicated to unsymmetric systems allows the three variants.
```

2022-08-20 02:52 UTC, dpo commented on docs/src/preconditioners.md
> +#### Unsymmetric linear systems
Are you including underdetermined consistent systems here? If not, then indicate "square unsymmetric systems".

2022-08-20 02:52 UTC, dpo commented on docs/src/preconditioners.md
> +#### Unsymmetric linear systems
Also, should we say "non-Hermitian" instead of "unsymmetric"?

2022-08-20 02:52 UTC, dpo commented on docs/src/preconditioners.md
> +#### Symmetric linear systems
```suggestion
#### Hermitian linear systems
```

2022-08-20 02:52 UTC, dpo commented on docs/src/preconditioners.md
> +When $A$ is symmetric, we can only use the centered / split preconditioning $LAL^Tx = Lb$.
If we want to preserve symmetry / hermicity.

2022-08-22 04:57 UTC, amontoison commented on docs/src/preconditioners.md
> +| Left preconditioning | Two-sided preconditioning       | Right preconditioning          |
Split preconditioning means that M = L = N', no?
It's equivalent to centered preconditioning for me while two-sided preconditioning is more generic.

2022-08-22 05:11 UTC, amontoison commented
I modified many things @dpo but we should have all informations related to preconditioners now.
https://juliasmoothoptimizers.github.io/Krylov.jl/previews/PR609/preconditioners/

2022-09-03 15:44 UTC, dpo requested changes
Fantastic description, thank you!

I just have a number of minor comments. We should read one more time after the corrections because I feel there may be some confusion between P and M (for the reader).

2022-09-03 15:44 UTC, dpo commented on docs/src/preconditioners.md
> +Preconditioning can be used to reduce the condition number of the problem or clusterize its eigenvalues for instance.
```suggestion
Preconditioning can be used to reduce the condition number of the problem or cluster its eigenvalues or singular values for instance.
```

2022-09-03 15:44 UTC, dpo commented on docs/src/preconditioners.md
> +The design of preconditioners is highly dependent on the origin of the problem and most preconditioners need to take application dependent information and structures into account.
```suggestion
The design of preconditioners is highly dependent on the origin of the problem and most preconditioners need to take application-dependent information and structure into account.
```

2022-09-03 15:44 UTC, dpo commented on docs/src/preconditioners.md
> +The construction of a preconditioner also necessitates a trade-off because we need to apply it at least once per iteration within a Krylov method.
```suggestion
The construction of a preconditioner necessitates trade-offs because we need to apply it at least once per iteration within a Krylov method.
```

2022-09-03 15:44 UTC, dpo commented on docs/src/preconditioners.md
> +We consider that $P_{\ell}^{-1}$ and $P_r^{-1}$ are the default preconditioners in Krylov.jl and that we can apply them with the operation $y \leftarrow P^{-1} * x$.
```suggestion
In Krylov.jl , we call $P_{\ell}^{-1}$ and $P_r^{-1}$ the preconditioners and we assume that we can apply them with the operation $y \leftarrow P^{-1} * x$.
```

2022-09-03 15:44 UTC, dpo commented on docs/src/preconditioners.md
> +Krylov.jl supports both approach thanks to the argument `ldiv` of the Krylov solvers.
```suggestion
Krylov.jl supports both approaches thanks to the argument `ldiv` of the Krylov solvers.
```

2022-09-03 15:44 UTC, dpo commented on docs/src/preconditioners.md
> +    A preconditioner only needs to support the operation `mul!(y, P⁻¹, x)` when `ldiv=false` or `ldiv!(y, P, x)` when `ldiv=true` to be used in Krylov.jl.
```suggestion
    A preconditioner only need support the operation `mul!(y, P⁻¹, x)` when `ldiv=false` or `ldiv!(y, P, x)` when `ldiv=true` to be used in Krylov.jl.
```

2022-09-03 15:44 UTC, dpo commented on docs/src/preconditioners.md
> +When $A$ is Hermitian, we can only use the centered preconditioning $L^{-1}AL^{-T}y = L^{-1}b$ with $x = L^{-T}y$.
```suggestion
When $A$ is Hermitian, we can only use centered preconditioning $L^{-1}AL^{-T}y = L^{-1}b$ with $x = L^{-T}y$.
```

2022-09-03 15:44 UTC, dpo commented on docs/src/preconditioners.md
> +This split preconditioning is a special case of two-sided preconditioning $P_{\ell} = L = P_r^T$ that maintains the hermicity of the linear systems.
```suggestion
Centered preconditioning is a special case of two-sided preconditionin with $P_{\ell} = L = P_r^T$ that maintains hermicity.
```

2022-09-03 15:44 UTC, dpo commented on docs/src/preconditioners.md
> +
```suggestion
However, there is no need to specify $L$ and one may specify $M$ directly.

```

2022-09-03 15:44 UTC, dpo commented on docs/src/preconditioners.md
> +| least-squares problem | $\min \\|b - Ax\\|^2_2$ | $\min \\|b - Ax\\|^2_{E^{-1}}$ |
```suggestion
| least-squares problem | $\min \\tfrac{1}{2} \\|b - Ax\\|^2_2$ | $\min \\tfrac{1}{2} \\|b - Ax\\|^2_{E^{-1}}$ |
```

2022-09-03 15:44 UTC, dpo commented on docs/src/preconditioners.md
> +| least-squares problem | $\min \\|b - Ax\\|^2_2 + \lambda^2 \\|x\\|^2_2$ | $\min \\|b - Ax\\|^2_{E^{-1}} + \lambda^2 \\|x\\|^2_F$ |
```suggestion
| least-squares problem | $\min \\tfrac{1}{2} \\|b - Ax\\|^2_2 + \\tfrac{1}{2} \lambda^2 \\|x\\|^2_2$ | $\min \\tfrac{1}{2} \\|b - Ax\\|^2_{E^{-1}} + \\tfrac{1}{2} \lambda^2 \\|x\\|^2_F$ |
```

2022-09-03 15:44 UTC, dpo commented on docs/src/preconditioners.md
> +| minimum-norm problem | $\min \\|x\\|^2_2~~\text{s.t.}~~Ax = b$ | $\min \\|x\\|^2_F~~\text{s.t.}~~Ax = b$ |
```suggestion
| minimum-norm problem | $\min \\tfrac{1}{2} \\|x\\|^2_2~~\text{s.t.}~~Ax = b$ | $\min \\tfrac{1}{2} \\|x\\|^2_F~~\text{s.t.}~~Ax = b$ |
```

2022-09-03 15:44 UTC, dpo commented on docs/src/preconditioners.md
> +| minimum-norm problem | $\min \\|x\\|^2_2 + \\|y\\|^2_2~~\text{s.t.}~~Ax + \lambda^2 y = b$ | $\min \\|x\\|^2_F + \\|y\\|^2_E~~\text{s.t.}~~Ax + \lambda^2 Ey = b$ |
```suggestion
| minimum-norm problem | $\min \\tfrac{1}{2} \\|x\\|^2_2 + \\tfrac{1}{2} \\|y\\|^2_2~~\text{s.t.}~~Ax + \lambda^2 y = b$ | $\min \\tfrac{1}{2} \\|x\\|^2_F + \\tfrac{1}{2} \\|y\\|^2_E~~\text{s.t.}~~Ax + \lambda^2 Ey = b$ |
```

2022-09-03 15:44 UTC, dpo commented on docs/src/preconditioners.md
> +where $E$ and $F$ are Hermitian and positive definite, [`TriCG`](@ref tricg) and [`TriMR`](@ref trimr) can take advantage of this form if preconditioners `M` and `N` that model the inverse of $E$ and
```suggestion
[`TriCG`](@ref tricg) and [`TriMR`](@ref trimr) can take advantage of the structure of Hermitian systems $Kz = d$ with the 2x2 block structure
```math
  \begin{bmatrix} \tau E & \phantom{-}A \\ A^T & \nu F \end{bmatrix} \begin{bmatrix} x \\ y \end{bmatrix} = \begin{bmatrix} b \\ c \end{bmatrix},
```
where $E$ and $F$ are Hermitian and positive definite, if preconditioners `M` and `N` that model the inverse of $E$ and $F$ are available.
```

2022-09-03 15:44 UTC, dpo commented on docs/src/preconditioners.md
> +[`GPMR`](@ref gpmr) can take advantage of this structure if we model the inverse of $M$ and $N$ with the help of preconditioners `C`, `D`, `E` and `F`.
```suggestion
[`GPMR`](@ref gpmr) can take advantage of the structure of general square systems $Kz = d$ with the 2x2 block structure
```math
  \begin{bmatrix} \lambda M & A \\ B & \mu N \end{bmatrix} \begin{bmatrix} x \\ y \end{bmatrix} = \begin{bmatrix} b \\ c \end{bmatrix},
```
if we model the inverse of $M$ and $N$ with the help of preconditioners `C`, `D`, `E` and `F`.
```

2022-09-03 15:44 UTC, dpo commented on docs/src/preconditioners.md
> +    The default value of a preconditioner in Krylov.jl is the identity operator `I`.
This should appear at the top.

2022-09-03 15:44 UTC, dpo commented on docs/src/preconditioners.md
> +- [IncompleteLU.jl](https://github.com/haampie/IncompleteLU.jl) implements the left-looking or Crout version of ILU decompositions.
```suggestion
- [IncompleteLU.jl](https://github.com/haampie/IncompleteLU.jl) implements the left-looking and Crout versions of ILU decompositions.
```

2022-09-03 15:44 UTC, dpo commented on docs/src/preconditioners.md
> +- [ILUZero.jl](https://github.com/mcovalt/ILUZero.jl)  is a Julia implementation of incomplete LU factorization with zero level of fill-in.
```suggestion
- [ILUZero.jl](https://github.com/mcovalt/ILUZero.jl) is a Julia implementation of incomplete LU factorization with zero level of fill-in. 
```

2022-09-06 23:30 UTC, amontoison commented
> Fantastic description, thank you!
> 
> I just have a number of minor comments. We should read one more time after the corrections because I feel there may be some confusion between P and M (for the reader).

@dpo I propose to replace all Aᵀ by Aᴴ.
Do you feel there may still be some confusion between P and M?

2022-09-06 23:49 UTC, dpo reviewed
Just a minor comment.

Yes, let's replace all Aᵀ with either A^* or A^H.

2022-09-06 23:49 UTC, dpo commented on docs/src/preconditioners.md
> +The solvers in Krylov.jl support preconditioners, i.e., transformations that modify a linear systems $Ax = b$ into an equivalent form that may yield faster convergence in finite-precision arithmetic.
```suggestion
The solvers in Krylov.jl support preconditioners, i.e., transformations that modify a linear system $Ax = b$ into an equivalent form that may yield faster convergence in finite-precision arithmetic.
```

2022-09-07 01:30 UTC, amontoison commented
I will use A^H because  A^* is only the conjugate matrix in some contexts.
https://mathworld.wolfram.com/ConjugateTranspose.html
https://mathworld.wolfram.com/ComplexConjugate.html

2022-09-07 18:12 UTC, merged