Add six Krylov processes
JuliaSmoothOptimizers/Krylov.jl pull request #618
Opened 2022-08-30 18:01 UTC by amontoison

2022-08-30 18:07 UTC, amontoison commented
https://juliasmoothoptimizers.github.io/Krylov.jl/previews/PR618/processes/ :sunglasses:

2022-08-30 18:10 UTC, amontoison commented on docs/src/processes.md
> +\end{bmatrix}
```suggestion
\end{bmatrix},
```

2022-08-31 12:49 UTC, tmigot reviewed
It looks good to me, thanks!

2022-08-31 12:49 UTC, tmigot commented on docs/src/processes.md
> +### Notations
Similar to the other pages in the doc, I think it misses `Krylov processes` as a title followed by one sentence explaining what is here.

2022-09-03 16:05 UTC, dpo requested changes
This will be of great help. I have the impression that the code is for the complex case, the algorithms are for the real case, and the description is a mixture :-).

2022-09-07 04:25 UTC, amontoison commented
@tmigot @dpo 
It's ready for a second round of review.

2022-09-10 15:43 UTC, dpo commented on src/krylov_processes.jl
> +      T[i-1,i] = βᵢ
shouldn't this be conjugated?

2022-09-10 15:43 UTC, dpo commented on docs/src/processes.md
> +Krylov processes are the foundations of Krylov methods, they generate bases of Krylov subspaces.
```suggestion
Krylov processes are the foundation of Krylov methods, they generate bases of Krylov subspaces.
```

2022-09-10 15:43 UTC, dpo commented on docs/src/processes.md
> +\end{bmatrix}
I think T should be Hermitian here.

2022-09-10 15:43 UTC, dpo commented on docs/src/processes.md
> +![symmetric_lanczos](./graphics/symmetric_lanczos.png)
Out of curiosity, does MathJax allow us to typeset algorithms?

2022-09-10 15:43 UTC, dpo commented on docs/src/processes.md
> +![symmetric_lanczos](./graphics/symmetric_lanczos.png)
Also, specify that $A = A^H$.

2022-09-10 15:43 UTC, dpo commented on docs/src/processes.md
> +After $k$ iterations of the symmetric Lanczos process, the situation may be summarized as
we should really call it the Hermitian Lanczos process.

2022-09-10 15:43 UTC, dpo commented on src/krylov_processes.jl
> +* `A`: a linear operator that models an Hermitian matrix of dimension n.
```suggestion
* `A`: a linear operator that models a Hermitian matrix of dimension n.
```

2022-09-10 15:43 UTC, dpo commented on src/krylov_processes.jl
> +* `T`: a sparse (k+1) × k tridiagonal matrix.
Hermitian.

2022-09-10 15:43 UTC, dpo commented on docs/src/processes.md
> +## Unsymmetric Lanczos
This is another bad name in the complex case. Maybe Non-Hermitian Lanczos?

2022-09-10 15:43 UTC, dpo commented on src/krylov_processes.jl
> +* `S`: a sparse (k+1) × k tridiagonal matrix.
Do we really need S here?

2022-09-10 15:43 UTC, dpo commented on src/krylov_processes.jl
> +* `A`: a linear operator that models a rectangular matrix of dimension n × m.
```suggestion
* `A`: a linear operator that models a matrix of dimension n × m.
```

2022-09-10 15:43 UTC, dpo commented on src/krylov_processes.jl
> +* `A`: a linear operator that models a rectangular matrix of dimension n × m.
```suggestion
* `A`: a linear operator that models a matrix of dimension n × m.
```

2022-09-10 15:43 UTC, dpo commented on src/krylov_processes.jl
> +* `A`: a linear operator that models a rectangular matrix of dimension n × m.
```suggestion
* `A`: a linear operator that models a matrix of dimension n × m.
```

2022-09-10 15:43 UTC, dpo commented on src/krylov_processes.jl
> +* `B`: a linear operator that models a rectangular matrix of dimension m × n.
```suggestion
* `B`: a linear operator that models a matrix of dimension m × n.
```

2022-09-15 22:03 UTC, amontoison commented on docs/src/processes.md
> +\end{bmatrix}
T has always real coefficients, it is symmetric.

2022-09-15 22:05 UTC, amontoison commented on src/krylov_processes.jl
> +      T[i-1,i] = βᵢ
No, because T has always real coefficients.
It's also the case for the bi-diagonal matrix in the Golub-Kahan process.

2022-09-15 22:10 UTC, amontoison commented on docs/src/processes.md
> +After $k$ iterations of the symmetric Lanczos process, the situation may be summarized as
```suggestion
After $k$ iterations of the Hermitian Lanczos process, the situation may be summarized as
```

2022-09-15 22:10 UTC, amontoison commented on docs/src/processes.md
> +## Unsymmetric Lanczos
```suggestion
## Non-Hermitian Lanczos
```

2022-09-15 22:10 UTC, amontoison commented on docs/src/processes.md
> +After $k$ iterations of the unsymmetric Lanczos process (also named the Lanczos biorthogonalization process), the situation may be summarized as
```suggestion
After $k$ iterations of the non-Hermitian Lanczos process (also named the Lanczos biorthogonalization process), the situation may be summarized as
```

2022-09-15 22:10 UTC, amontoison commented on docs/src/processes.md
> +## Symmetric Lanczos
```suggestion
## Hermitian Lanczos
```

2022-09-15 22:36 UTC, amontoison commented on docs/src/processes.md
> +![symmetric_lanczos](./graphics/symmetric_lanczos.png)
> Out of curiosity, does MathJax allow us to typeset algorithms?

I will [pseudocode.js](https://github.com/SaswatPadhi/pseudocode.js).

2022-09-23 14:19 UTC, amontoison commented
With #637, we should be able to run the processes on GPUs.

2022-09-28 04:15 UTC, merged