add imput and output arguments in all docstrings
JuliaSmoothOptimizers/Krylov.jl pull request #647
Opened 2022-10-03 14:33 UTC by amontoison

I will add a `#### Optional argument(s)` section when #564 will be close.
The final goal is to also add `#### Keyword arguments` and `#### Stopping conditions` in all docstring such that we can do a release 1.0.

2022-10-03 15:19 UTC, dpo commented on src/bicgstab.jl
> +* `A`: a linear operator that models a matrix of dimension n.
```suggestion
* `A`: a linear operator that models a matrix of dimension n;
```

2022-10-03 15:19 UTC, dpo commented on src/bicgstab.jl
> +* `A`: a linear operator that models a matrix of dimension n.
I don't see where n is defined.

2022-10-03 15:19 UTC, dpo commented on src/bicgstab.jl
> +* `x`: a dense vector of length n.
```suggestion
* `x`: a dense vector of length n;
```

2022-10-03 15:27 UTC, amontoison commented on src/bicgstab.jl
> +* `A`: a linear operator that models a matrix of dimension n.
`n` is not a parameter but I use it to say that the solution is of length `n` in the docstring.
When we have multiple solution, which is the case for `TriCG`, `TriMR` or `GPMR`, it helps to give the length of output vectors.

2022-10-03 15:56 UTC, dpo commented on src/bicgstab.jl
> +* `A`: a linear operator that models a matrix of dimension n.
I know but n doesn't seem to be defined in the docstring. It should say somewhere that Ax=b is a system of size n.

2022-10-03 18:03 UTC, dpo commented
> Is there a reason why you use `####` instead of just `#`?

The font size would be obnoxiously large in the docs.

2022-10-04 21:52 UTC, dpo requested changes

2022-10-04 21:52 UTC, dpo commented on src/cgls.jl
> +of size n × m using the Conjugate Gradient (CG) method, where λ ≥ 0 is a regularization
m x n

2022-10-04 21:52 UTC, dpo commented on src/gpmr.jl
> +of size (n+m) × (n+m) where λ and μ are real or complex numbers.
give the size of A and B instead

2022-10-05 02:11 UTC, amontoison commented on src/cgls.jl
> +of size n × m using the Conjugate Gradient (CG) method, where λ ≥ 0 is a regularization
Do you want to use `m x n` when `A` has more rows than columns or when A is rectangular?

2022-10-05 17:29 UTC, dpo commented on src/cgls.jl
> +of size n × m using the Conjugate Gradient (CG) method, where λ ≥ 0 is a regularization
You grab `m, n` as the size of A : https://github.com/JuliaSmoothOptimizers/Krylov.jl/pull/647/files/a2e5796af0bdee8d225347cbd9f984fd554a72c2#diff-695bcdad4090fc22200b17203cb5318c0aa0f12e11a6ecdc048ea445ce5a22f1R96

But yes, a matrix is always m x n :-)

2022-10-06 14:35 UTC, amontoison commented on src/gpmr.jl
> +of size (n+m) × (n+m) where λ and μ are real or complex numbers.
What do you think of:
```
Given matrices `A` of dimension m × n and `B` of dimension n × m,
GPMR solves the unsymmetric partitioned linear system

    [ λIₘ   A  ] [ x ] = [ b ]
    [  B   μIₙ ] [ y ]   [ c ],

of size (n+m) × (n+m) where λ and μ are real or complex numbers.
```
and
```
Given a matrix `A` of dimension m × n, TriCG / TriMR solves the symmetric linear system

    [ τE    A ] [ x ] = [ b ]
    [  Aᴴ  νF ] [ y ]   [ c ],

of size (n+m) × (n+m) where τ and ν are real numbers, E = M⁻¹ ≻ 0, F = N⁻¹ ≻ 0.
```
?

2022-10-07 02:55 UTC, merged