StaticArrays support
JuliaSmoothOptimizers/Krylov.jl pull request #768
Opened 2023-08-08 15:27 UTC by amontoison

2023-08-08 20:15 UTC, gdalle requested changes

2023-08-08 20:15 UTC, gdalle commented on src/krylov_utils.jl
> +  if S.name.name == :Zeros || S.name.name == :Ones || S.name.name == :SArray || S.name.name == :MArray || S.name.name == :SizedArray
I think `:FieldArray` is also a valid subtype of `StaticVector`
```julia
julia> subtypes(StaticVector)
5-element Vector{Any}:
 FieldArray{Tuple{N}, T, 1} where {N, T}
 MArray{Tuple{N}, T, 1} where {N, T}
 SArray{Tuple{N}, T, 1} where {N, T}
 SizedArray{Tuple{N}, T, 1, M} where {N, T, M}
 StaticArrays.SUnitRange
```

2023-08-08 20:16 UTC, gdalle commented
This works for my use case, thanks for the rapid fix! I'm gonna try to demo a more principled version over on #767

2023-08-08 20:17 UTC, gdalle commented on test/test_extensions.jl
> +@testset "StaticArrays" begin
Would it make sense to also test other array formats like FillArrays? Test dependencies are free

2023-08-09 10:43 UTC, gdalle commented
Given #769 I really think the right fix is #767 instead of editing this single line forever with manual type names

2023-08-09 12:31 UTC, gdalle commented on src/krylov_utils.jl
> +  if S.name.name == :Zeros || S.name.name == :Ones || S.name.name == :SArray || S.name.name == :MArray || S.name.name == :SizedArray
And if we could add `:ComponentArray` that would solve all my immediate problems

2023-08-09 17:34 UTC, amontoison commented on test/test_extensions.jl
> +@testset "StaticArrays" begin
Yes, I will do that with another PR.

2023-08-09 17:34 UTC, merged